"""create grain_purchases and grain_inventory tables

Revision ID: d2b4967bdc82
Revises: f549345b2818
Create Date: 2026-07-15 20:39:32.017175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b4967bdc82'
down_revision: Union[str, None] = 'f549345b2818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grain_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grain_type_id', sa.Integer(), nullable=False),
    sa.Column('total_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['grain_type_id'], ['grain_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grain_type_id')
    )
    op.create_table('grain_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('grain_type_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grain_type_id'], ['grain_types.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grain_purchases')
    op.drop_table('grain_inventory')
    # ### end Alembic commands ###
