"""add is_active to products

Revision ID: e62fdae69bc3
Revises: b1e3a0be2352
Create Date: 2026-08-14 08:37:44.803898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62fdae69bc3'
down_revision: Union[str, None] = 'b1e3a0be2352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
    )
    op.execute('UPDATE products SET is_active = TRUE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
